#1   WEP
2   stub THAIENABLE
3   stub THAIGETCHARPLACEMENT
4   stub THAIDELETEFONT
5   stub THAISELECTFONT
6   stub THAIGETTEXTEXTENT
7   stub THAIEXTTEXTOUT
8   stub THAIGETCHARWIDTH
9   stub THAINETASKNOTIFYCALLBACK
10  stub REGISTERNETASKCALLBACK
11  stub UNREGISTERNETASKCALLBACK
20  stub THAIEDITWNDPROC
21  stub THAITABBEDTEXT
22  stub THAIDRAWTEXT
23  stub THAIPSMTEXTOUT
#30  stub DLLENTRYPOINT
#31  stub THK_THUNKDATA16
104 stub FINDTHAIWORDBREAK
